const KEY="hrgen_lis_v1";
const DEFAULT_TESTS=[
{id:"t1",name:"CBC",dept:"Hematology",price:350,unit:"",low:null,high:null},
{id:"t2",name:"Hemoglobin",dept:"Hematology",price:120,unit:"g/dL",low:12,high:16},
{id:"t3",name:"Blood Sugar Fasting",dept:"Biochemistry",price:80,unit:"mg/dL",low:70,high:100},
{id:"t4",name:"HbA1c",dept:"Biochemistry",price:450,unit:"%",low:4,high:5.6},
{id:"t5",name:"TSH",dept:"Endocrinology",price:300,unit:"uIU/mL",low:0.4,high:4},
{id:"t6",name:"Lipid Profile",dept:"Biochemistry",price:600,unit:"",low:null,high:null},
{id:"t7",name:"Vitamin D",dept:"Biochemistry",price:900,unit:"ng/mL",low:30,high:100},
{id:"t8",name:"LFT",dept:"Biochemistry",price:500,unit:"",low:null,high:null},
{id:"t9",name:"KFT",dept:"Biochemistry",price:500,unit:"",low:null,high:null}
];
function empty(){return{settings:{labName:"HRGen Diagnostics",address:"Aligarh",phone:"",wa:""},users:[{username:"admin",password:"admin123",role:"Admin"}],tests:DEFAULT_TESTS,bills:[],outbox:[],session:null}}
let DB=JSON.parse(localStorage.getItem(KEY)||"null")||empty();
let selected=[],activeBillId=null;
const $=id=>document.getElementById(id);
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
const today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(KEY,JSON.stringify(DB));updateBadges()}
function updateBadges(){const on=navigator.onLine;$("netBadge").textContent=on?"ONLINE":"OFFLINE";$("netBadge").className="net "+(on?"online":"offline");$("syncBadge").textContent="Outbox "+(DB.outbox||[]).filter(x=>x.status==="pending").length}
function showLogin(s){$("loginScreen").classList.toggle("hidden",!s);$("appScreen").classList.toggle("hidden",s)}
function go(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===p));$("page-"+p).classList.remove("hidden");$("pageTitle").textContent={dashboard:"Dashboard",newbill:"New Bill",results:"Result Entry",masters:"Test Master",reports:"Reports",settings:"Settings"}[p];
if(p==="dashboard")renderDash();if(p==="newbill")renderTests();if(p==="masters")renderMasters();if(p==="reports")renderReports();if(p==="settings")fillSet()}
function renderDash(){const t=today(),tb=DB.bills.filter(b=>b.date===t);$("statBills").textContent=tb.length;$("statPatients").textContent=new Set(tb.map(b=>b.mobile)).size;$("statPending").textContent=DB.bills.filter(b=>b.status!=="Reported").length;$("statCash").textContent=money(tb.reduce((s,b)=>s+Number(b.payable),0));$("dashBills").innerHTML=tableBills(tb.slice(-8).reverse())}
function tableBills(list){if(!list.length)return"<p class='muted'>No records</p>";return"<table><tr><th>Bill</th><th>Patient</th><th>Amt</th><th>Status</th><th></th></tr>"+list.map(b=>`<tr><td>${b.no}</td><td>${b.name}</td><td>${money(b.payable)}</td><td>${b.status}</td><td><button class=\"btn-outline\" data-open=\"${b.id}\">Open</button></td></tr>`).join("")+"</table>"}
function renderTests(){const q=($("testSearch").value||"").toLowerCase();$("testPick").innerHTML=DB.tests.filter(t=>t.name.toLowerCase().includes(q)).map(t=>`<span class=\"chip\" data-add=\"${t.id}\">${t.name} · ${money(t.price)}</span>`).join("");renderSel()}
function renderSel(){const rows=selected.map((id,i)=>{const t=DB.tests.find(x=>x.id===id);return`<tr><td>${i+1}</td><td>${t.name}</td><td>${money(t.price)}</td><td><button class=\"btn-ghost\" data-del=\"${id}\">X</button></td></tr>`}).join("");$("selectedTests").innerHTML=selected.length?"<table>"+rows+"</table>":"<p class='muted'>Select tests</p>";const sub=selected.reduce((s,id)=>s+Number(DB.tests.find(t=>t.id===id).price),0);const d=Number($("discount").value||0);$("subTotal").textContent=money(sub);$("finalAmt").textContent=money(Math.max(0,sub-d))}
function saveBill(){const name=$("pName").value.trim(),mobile=$("pMobile").value.trim();if(!name||mobile.length<10)return alert("Name + 10 digit mobile");if(!selected.length)return alert("Select test");const tests=selected.map(id=>{const t=DB.tests.find(x=>x.id===id);return{...t,value:"",flag:""}});const sub=tests.reduce((s,t)=>s+Number(t.price),0),disc=Number($("discount").value||0);const bill={id:"b"+Date.now(),no:"HRG"+String(DB.bills.length+1).padStart(5,"0"),date:today(),name,mobile,age:$("pAge").value,gender:$("pGender").value,doctor:$("pDoctor").value,address:$("pAddress").value,tests,subtotal:sub,discount:disc,payable:Math.max(0,sub-disc),status:"Pending",interpretation:""};DB.bills.push(bill);DB.outbox=DB.outbox||[];DB.outbox.push({id:"o"+Date.now(),action:"CREATE_BILL",status:"pending"});save();selected=[];["pMobile","pName","pAge","pDoctor","pAddress"].forEach(id=>$(id).value="");$("discount").value=0;renderSel();openBill(bill.id)}
function openBill(id){const b=DB.bills.find(x=>x.id===id);if(!b)return;activeBillId=id;$("billPrint").innerHTML=`<div class=\"bill-sheet\"><h2>${DB.settings.labName}</h2><p>${DB.settings.address}</p><hr/><p><b>${b.no}</b> · ${b.date}</p><p>${b.name} (${b.age}/${b.gender}) ${b.mobile}</p><table><tr><th>Test</th><th>Amt</th><th>Value</th><th>Flag</th></tr>${b.tests.map(t=>`<tr><td>${t.name}</td><td>${money(t.price)}</td><td>${t.value||\"-\"}</td><td>${t.flag||\"-\"}</td></tr>`).join(\"\")}</table><p><b>Payable ${money(b.payable)}</b></p>${b.interpretation?`<p>${b.interpretation}</p>`:\"\"}</div>`;$("printModal").classList.remove("hidden")}
function flag(t,v){if(v===\"\"||t.low==null)return\"N\";const n=Number(v);if(n<t.low)return\"L\";if(n>t.high)return\"H\";return\"N\"}
function loadResult(){const q=($("resultSearch").value||\"\").toLowerCase();const b=DB.bills.find(x=>x.no.toLowerCase()===q||x.name.toLowerCase().includes(q)||x.mobile.includes(q))||DB.bills.filter(x=>x.status!==\"Reported\").slice(-1)[0];if(!b){$("resultHead").textContent=\"Not found\";return}activeBillId=b.id;$("resultHead").textContent=`${b.no} · ${b.name} · ${b.status}`;$("interpretation").value=b.interpretation||\"\";$("resultTable").innerHTML=\"<table><tr><th>Test</th><th>Ref</th><th>Value</th><th>Flag</th></tr>\"+b.tests.map((t,i)=>`<tr><td>${t.name}</td><td>${t.low!=null?t.low+\"-\"+t.high:\"\"}</td><td><input data-val=\"${i}\" value=\"${t.value||\"\"}\"/></td><td class=\"flag-${t.flag||\"N\"}\" id=\"flag-${i}\">${t.flag||\"N\"}</td></tr>`).join(\"\")+\"</table>\"}
function saveResult(){const b=DB.bills.find(x=>x.id===activeBillId);if(!b)return alert(\"Load bill\");b.tests.forEach((t,i)=>{const inp=document.querySelector(`[data-val=\"${i}\"]`);t.value=inp?inp.value:t.value;t.flag=flag(t,t.value)});b.interpretation=$(\"interpretation\").value;b.status=\"Reported\";DB.outbox.push({id:\"o\"+Date.now(),action:\"SAVE_RESULT\",status:\"pending\"});save();alert(\"Saved\");openBill(b.id)}
function renderMasters(){$(\"masterTable\").innerHTML=\"<table><tr><th>Test</th><th>Dept</th><th>Price</th></tr>\"+DB.tests.map(t=>`<tr><td>${t.name}</td><td>${t.dept}</td><td>${money(t.price)}</td></tr>`).join(\"\")+\"</table>\"}
function addTest(){const name=$(\"mName\").value.trim();if(!name)return;DB.tests.push({id:\"t\"+Date.now(),name,dept:$(\"mDept\").value||\"General\",price:Number($(\"mPrice\").value||0),unit:$(\"mUnit\").value,low:$(\"mLow\").value===\"\"?null:Number($(\"mLow\").value),high:$(\"mHigh\").value===\"\"?null:Number($(\"mHigh\").value)});save();renderMasters()}
function renderReports(){let list=[...DB.bills].reverse();const f=$(\"repFrom\").value,t=$(\"repTo\").value;if(f)list=list.filter(b=>b.date>=f);if(t)list=list.filter(b=>b.date<=t);$(\"reportTable\").innerHTML=tableBills(list)}
function fillSet(){$(\"sLabName\").value=DB.settings.labName||\"\";$(\"sAddress\").value=DB.settings.address||\"\";$(\"sPhone\").value=DB.settings.phone||\"\";$(\"sWa\").value=DB.settings.wa||\"\"}
function saveSet(){DB.settings={labName:$(\"sLabName\").value,address:$(\"sAddress\").value,phone:$(\"sPhone\").value,wa:$(\"sWa\").value};save();alert(\"Saved\")}
document.getElementById(\"loginForm\").onsubmit=e=>{e.preventDefault();const u=DB.users.find(x=>x.username===$(\"username\").value&&x.password===$(\"password\").value);if(!u)return alert(\"Wrong login\");DB.session={username:u.username,role:u.role};save();showLogin(false);$(\"userPill\").textContent=u.username;go(\"dashboard\")};
document.addEventListener(\"click\",e=>{const n=e.target.closest(\".nav-btn\");if(n)go(n.dataset.page);if(e.target.id===\"logoutBtn\"){DB.session=null;save();showLogin(true)}
if(e.target.dataset.goto)go(e.target.dataset.goto);if(e.target.dataset.add&&!selected.includes(e.target.dataset.add)){selected.push(e.target.dataset.add);renderSel()}
if(e.target.dataset.del){selected=selected.filter(id=>id!==e.target.dataset.del);renderSel()}
if(e.target.id===\"saveBillBtn\")saveBill();if(e.target.id===\"loadResultBtn\")loadResult();if(e.target.id===\"saveResultBtn\")saveResult();
if(e.target.id===\"addTestBtn\")addTest();if(e.target.id===\"filterRepBtn\")renderReports();if(e.target.id===\"saveSetBtn\")saveSet();
if(e.target.dataset.open)openBill(e.target.dataset.open);if(e.target.id===\"closePrint\")$(\"printModal\").classList.add(\"hidden\");
if(e.target.id===\"doPrintBtn\")window.print();if(e.target.id===\"waBtn\"){const b=DB.bills.find(x=>x.id===activeBillId);if(!b)return;const num=(b.mobile.length===10?\"91\"+b.mobile:b.mobile);window.open(\"https://wa.me/\"+num+\"?text=\"+encodeURIComponent(DB.settings.labName+\" Bill \"+b.no+\" \"+b.name+\" \"+money(b.payable)),\"_blank\")}
if(e.target.id===\"exportBtn\"){const a=document.createElement(\"a\");a.href=URL.createObjectURL(new Blob([JSON.stringify(DB)],{type:\"application/json\"}));a.download=\"hrgen-backup.json\";a.click()}
if(e.target.id===\"importBtn\")$(\"importFile\").click()});
document.addEventListener(\"change\",e=>{if(e.target.id===\"importFile\"&&e.target.files[0]){const r=new FileReader();r.onload=()=>{DB=Object.assign(empty(),JSON.parse(r.result));save();go(\"dashboard\");alert(\"Imported\")};r.readAsText(e.target.files[0])}});
document.addEventListener(\"input\",e=>{if(e.target.id===\"testSearch\")renderTests();if(e.target.id===\"discount\")renderSel();if(e.target.dataset.val!=null){const i=+e.target.dataset.val,b=DB.bills.find(x=>x.id===activeBillId);if(!b)return;const f=flag(b.tests[i],e.target.value);const el=$(\"flag-\"+i);if(el){el.textContent=f;el.className=\"flag-\"+f}}});
window.addEventListener(\"online\",updateBadges);window.addEventListener(\"offline\",updateBadges);
if(DB.session){showLogin(false);$(\"userPill\").textContent=DB.session.username;go(\"dashboard\")}else showLogin(true);updateBadges();
